---
namespace: business
name: custom
version: 1.0.0
readme: README.md
authors:
  - Ansible Business Process
description: Custom filter plugins and other helpers that don't fit under a service-specific collection.
license:
  - GPL-3.0-or-later
tags:
  - filter
  - salesforce
repository: https://github.com/zjleblanc/ansible-support-analyzer
issues: https://github.com/zjleblanc/ansible-support-analyzer/issues
build_ignore: []
